//! A stable fingerprint of a language definition's *value space*.
//!
//! A component's own shape changes are deliberate, so an integer written by
//! hand ([`crate::component::AnalysisComponent::output_version`]) tracks them.
//! Language definitions do not work that way: adding a variant to
//! `TurkishMorphemeFunction` changes what stored cards can legally contain, and
//! the person adding that variant is thinking about Turkish grammar, not about
//! rows in a database. Any version that depends on them remembering to bump a
//! counter will drift out of date, silently, on exactly the change that matters.
//!
//! So this version is *derived* rather than written. The catalogs generated by
//! `#[derive(MorphologyInfo)]` and `#[derive(MorphemeFunctionCatalog)]` already
//! enumerate the whole value space at compile time; hashing them yields a digest
//! that moves on its own whenever the space moves.
//!
//! # What a digest can and cannot do
//!
//! A digest says *different*, never *how* different. There is no migration to be
//! written from a hash — it is a staleness signal, not a dispatch key. Sections
//! whose digest no longer matches the current language are still served as-is;
//! the mismatch only marks their analysis as produced under a definition that no
//! longer exists.
//!
//! # What is hashed
//!
//! Only the parts a reader could choke on: group and variant keys, field names,
//! and the exhaustive value lists of closed fields. Display labels are excluded
//! — rewording a label changes no stored data, and a digest that moved on prose
//! would cry wolf. Everything is sorted before hashing, so reordering variants
//! in a source file is not a change either.

use std::fmt;

use crate::aggregable::{FieldDescriptor, FieldKind};
use crate::traits::{IsoLang, MorphemeFunctionCatalog, MorphologyCatalog};

/// Field separator inside one descriptor line. A control character, so it can
/// never occur in a Rust identifier or serde rename and blur two fields into one.
const UNIT: char = '\u{1f}';

/// A language definition's value-space fingerprint, rendered as `tur:9f1e3c...`.
///
/// Stored alongside sections produced under that definition. Compare with
/// [`PartialEq`]; a mismatch means the section was analysed under a different
/// value space, and nothing more specific than that.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LanguageDigest {
    iso_code: IsoLang,
    hash: u64,
}

impl LanguageDigest {
    /// Compute the digest for a language definition's morphology and morpheme
    /// function catalogs.
    #[must_use]
    pub fn compute<M, F>(iso_code: IsoLang) -> Self
    where
        M: MorphologyCatalog,
        F: MorphemeFunctionCatalog,
    {
        let mut lines = Vec::new();

        for group in M::group_descriptors() {
            for dimension in &group.dimensions {
                lines.push(descriptor_line("morphology", &group.key, dimension));
            }
        }
        for variant in F::function_descriptors() {
            for dimension in &variant.dimensions {
                lines.push(descriptor_line(
                    "morpheme_function",
                    &variant.key,
                    dimension,
                ));
            }
        }

        // Sorting makes the digest invariant to declaration order: moving a
        // variant up a file is not a change to what cards may contain.
        lines.sort_unstable();
        lines.dedup();

        let mut hasher = Fnv1a::new();
        for line in &lines {
            hasher.write(line.as_bytes());
            // Hash the separator too, so ("ab", "c") cannot collide with ("a", "bc").
            hasher.write(b"\n");
        }

        Self {
            iso_code,
            hash: hasher.finish(),
        }
    }

    /// The ISO 639-3 code this digest was computed for.
    #[must_use]
    pub const fn iso_code(&self) -> IsoLang {
        self.iso_code
    }

    /// The raw hash of the value space, without the language prefix.
    #[must_use]
    pub const fn hash(&self) -> u64 {
        self.hash
    }
}

impl fmt::Display for LanguageDigest {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}:{:016x}", self.iso_code.to_639_3(), self.hash)
    }
}

impl serde::Serialize for LanguageDigest {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_str(self)
    }
}

/// One canonical line describing a single field of the value space.
fn descriptor_line(section: &str, owner_key: &str, dimension: &FieldDescriptor) -> String {
    let mut line = format!("{section}{UNIT}{owner_key}{UNIT}{}{UNIT}", dimension.name);
    match dimension.kind {
        FieldKind::Open => line.push_str("open"),
        FieldKind::Closed(variants) => {
            let mut variants: Vec<&str> = variants.to_vec();
            variants.sort_unstable();
            line.push_str("closed=");
            line.push_str(&variants.join(","));
        }
    }
    line
}

/// FNV-1a, 64-bit.
///
/// Deliberately not `std::hash::DefaultHasher`: digests are written to the
/// database and compared against digests computed by a later build, so the
/// function has to be byte-stable forever. `std` explicitly declines to
/// guarantee that across releases. FNV-1a is fully specified in a dozen lines
/// and can never drift under us.
struct Fnv1a(u64);

impl Fnv1a {
    const OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
    const PRIME: u64 = 0x0000_0100_0000_01b3;

    const fn new() -> Self {
        Self(Self::OFFSET_BASIS)
    }

    fn write(&mut self, bytes: &[u8]) {
        for &byte in bytes {
            self.0 ^= u64::from(byte);
            self.0 = self.0.wrapping_mul(Self::PRIME);
        }
    }

    const fn finish(&self) -> u64 {
        self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::traits::{FunctionVariantSchema, MorphologyGroupSchema};

    fn field(name: &str, kind: FieldKind) -> FieldDescriptor {
        FieldDescriptor {
            name: name.to_string(),
            kind,
        }
    }

    struct Morph;
    impl MorphologyCatalog for Morph {
        fn group_descriptors() -> Vec<MorphologyGroupSchema> {
            vec![MorphologyGroupSchema {
                key: "noun".into(),
                label: "Noun".into(),
                dimensions: vec![
                    field("lemma", FieldKind::Open),
                    field("case", FieldKind::Closed(&["nominative", "accusative"])),
                ],
            }]
        }
    }

    /// Same value space as [`Morph`], with the closed variants listed in the
    /// other order and the display label reworded.
    struct MorphReordered;
    impl MorphologyCatalog for MorphReordered {
        fn group_descriptors() -> Vec<MorphologyGroupSchema> {
            vec![MorphologyGroupSchema {
                key: "noun".into(),
                label: "Substantive".into(),
                dimensions: vec![
                    field("case", FieldKind::Closed(&["accusative", "nominative"])),
                    field("lemma", FieldKind::Open),
                ],
            }]
        }
    }

    /// [`Morph`] plus one new case — the change that must be detected.
    struct MorphExtraCase;
    impl MorphologyCatalog for MorphExtraCase {
        fn group_descriptors() -> Vec<MorphologyGroupSchema> {
            vec![MorphologyGroupSchema {
                key: "noun".into(),
                label: "Noun".into(),
                dimensions: vec![
                    field("lemma", FieldKind::Open),
                    field(
                        "case",
                        FieldKind::Closed(&["nominative", "accusative", "locative"]),
                    ),
                ],
            }]
        }
    }

    struct Func;
    impl MorphemeFunctionCatalog for Func {
        fn function_descriptors() -> Vec<FunctionVariantSchema> {
            vec![FunctionVariantSchema {
                key: "case".into(),
                label: "Case".into(),
                dimensions: vec![field("value", FieldKind::Closed(&["dative"]))],
            }]
        }
    }

    #[test]
    fn digest_is_stable_across_runs() {
        assert_eq!(
            LanguageDigest::compute::<Morph, ()>(IsoLang::Tur),
            LanguageDigest::compute::<Morph, ()>(IsoLang::Tur)
        );
    }

    #[test]
    fn digest_ignores_declaration_order_and_labels() {
        assert_eq!(
            LanguageDigest::compute::<Morph, ()>(IsoLang::Tur),
            LanguageDigest::compute::<MorphReordered, ()>(IsoLang::Tur),
            "reordering variants and rewording a label changes no stored data"
        );
    }

    #[test]
    fn digest_moves_when_a_variant_is_added() {
        assert_ne!(
            LanguageDigest::compute::<Morph, ()>(IsoLang::Tur),
            LanguageDigest::compute::<MorphExtraCase, ()>(IsoLang::Tur),
            "a new case widens what stored cards may contain"
        );
    }

    #[test]
    fn digest_moves_when_morpheme_functions_change() {
        assert_ne!(
            LanguageDigest::compute::<Morph, ()>(IsoLang::Tur),
            LanguageDigest::compute::<Morph, Func>(IsoLang::Tur),
            "morpheme functions are part of the value space"
        );
    }

    #[test]
    fn digest_distinguishes_languages_sharing_a_value_space() {
        let turkish = LanguageDigest::compute::<Morph, ()>(IsoLang::Tur);
        let polish = LanguageDigest::compute::<Morph, ()>(IsoLang::Pol);

        assert_ne!(turkish, polish);
        assert_eq!(
            turkish.hash(),
            polish.hash(),
            "the hash covers the value space; the ISO code separates the languages"
        );
    }

    #[test]
    fn digest_renders_as_prefixed_hex() {
        let rendered = LanguageDigest::compute::<Morph, ()>(IsoLang::Tur).to_string();

        let (iso, hash) = rendered.split_once(':').expect("digest is prefixed");
        assert_eq!(iso, "tur");
        assert_eq!(hash.len(), 16, "u64 rendered as zero-padded hex");
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn field_boundaries_cannot_be_blurred() {
        // Without a separator between name and kind, ("ab", closed=[]) and
        // ("a", closed=["b"]) could render to the same bytes.
        let joined = descriptor_line("morphology", "noun", &field("ab", FieldKind::Closed(&[])));
        let split = descriptor_line("morphology", "noun", &field("a", FieldKind::Closed(&["b"])));

        assert_ne!(joined, split);
    }
}
