use std::fmt::Debug;
use std::hash::Hash;

use serde::{Deserialize, Serialize};

use crate::domain::{ExtractedFeature, MultiwordExpression};
use crate::traits::{LinguisticDefinition, MorphologyInfo};

// ─── Morpheme types ───────────────────────────────────────────────────────────

/// Static definition of a grammatical morpheme in a language's inventory.
///
/// `F` = the language's `GrammaticalFunction` wrapper enum.
/// `P` = the language's `PosTag` type (generated by `#[derive(MorphologyInfo)]`).
pub struct MorphemeDefinition<F: 'static, P: 'static> {
    /// Archiphonemic notation identifying the morpheme (e.g., `"DA"`, `"mA"`, `"(y)AcAk"`).
    pub base_form: &'static str,
    /// All grammatical functions this morpheme can serve.
    pub functions: &'static [F],
    /// POS categories this morpheme attaches to. Same type as `MorphologyInfo::PosTag`.
    pub applies_to: &'static [P],
}

/// A single morpheme instance extracted by the LLM from a word.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(bound = "F: schemars::JsonSchema")]
pub struct ExtractedMorpheme<F> {
    /// The allomorph as it actually appears in the word (e.g., `"me"` for the morpheme `"mA"`).
    pub surface: String,
    /// Archiphonemic base form identifying which morpheme this is (validated against inventory).
    pub base_form: String,
    /// The grammatical function this morpheme serves in context.
    pub function: F,
}

/// All morphemes extracted from a single word.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(bound = "F: schemars::JsonSchema")]
pub struct WordSegmentation<F> {
    /// Surface form of the whole word.
    pub word: String,
    /// Ordered list of extracted morphemes (excluding the root/stem, which is in `lemma`).
    pub morphemes: Vec<ExtractedMorpheme<F>>,
}

// ─── Agglutinative trait ──────────────────────────────────────────────────────

/// Opt-in trait for agglutinative languages.
///
/// Provides the morpheme-specific methods: static inventory, LLM directives, and
/// typed validation. The three extension points on `LinguisticDefinition`
/// (`build_extraction_schema`, `extra_extraction_directives`, `post_process_extraction`)
/// should delegate here.
pub trait Agglutinative: LinguisticDefinition
where
    <Self::Morphology as MorphologyInfo>::PosTag: Debug + Clone + Copy + PartialEq + Eq + Hash + 'static,
    Self::GrammaticalFunction: Debug + Clone + PartialEq
        + Serialize
        + for<'de> Deserialize<'de>
        + schemars::JsonSchema
        + Send
        + Sync
        + 'static,
{
    /// The full static inventory of morphemes for this language.
    fn morpheme_inventory() -> &'static [MorphemeDefinition<
        Self::GrammaticalFunction,
        <Self::Morphology as MorphologyInfo>::PosTag,
    >];

    /// Directives for the LLM explaining how to fill `morpheme_segmentation`.
    fn morpheme_directives(&self) -> String;

    /// Parse and validate morpheme segmentation from the LLM response.
    fn validate_and_enrich(
        &self,
        segmentation: &mut Option<Vec<WordSegmentation<Self::GrammaticalFunction>>>,
    ) -> Result<(), String> {
        let Some(segs) = segmentation.as_mut() else {
            return Ok(());
        };

        let mut errors = Vec::new();
        let inventory = Self::morpheme_inventory();

        for seg in segs.iter_mut() {
            let word = &seg.word;
            for morpheme in seg.morphemes.iter_mut() {
                let definition = inventory
                    .iter()
                    .find(|d| d.base_form == morpheme.base_form);

                let Some(def) = definition else {
                    errors.push(format!(
                        "Unknown morpheme base_form '{}' for word '{}'. Use only base_forms from the inventory.",
                        morpheme.base_form, word
                    ));
                    continue;
                };

                if !def.functions.contains(&morpheme.function) {
                    if def.functions.len() == 1 {
                        morpheme.function = def.functions[0].clone();
                    } else {
                        errors.push(format!(
                            "Invalid function {:?} for morpheme '{}' in word '{}'. Valid functions: {:?}",
                            morpheme.function, morpheme.base_form, word, def.functions
                        ));
                    }
                }
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors.join("\n"))
        }
    }

    /// Generate the full extraction JSON schema (base morphology + morpheme fields).
    fn build_full_schema() -> serde_json::Value
    where
        Self::Morphology: schemars::JsonSchema,
    {
        let r#gen = schemars::SchemaGenerator::default();
        let schema = r#gen.into_root_schema_for::<
            FeatureExtractionResponse<Self::Morphology, Self::GrammaticalFunction>
        >();
        serde_json::to_value(&schema).unwrap()
    }
}

// Lives in `panini-core` so that `LinguisticDefinition::build_extraction_schema()`
// can reference it without a circular dependency.
#[derive(Debug, Clone, Serialize, Deserialize, schemars::JsonSchema)]
#[schemars(bound = "M: schemars::JsonSchema, F: schemars::JsonSchema")]
#[serde(bound(deserialize = "M: for<'de2> Deserialize<'de2>, F: for<'de2> Deserialize<'de2>"))]
pub struct FeatureExtractionResponse<M, F = ()> {
    /// PEDAGOGICAL EXPLANATION FORMAT:
    /// Write the ENTIRE explanation in the learner's interface language.
    /// The field must be an HTML string (no markdown). Structure it as follows:
    ///
    /// 1. **Translations**: Start with literal and natural translations (if they differ).
    ///    Use: <p><b>Translations:</b><br><i>Lit:</i> ...<br><i>Nat:</i> ...</p>
    ///
    /// 2. **Analysis**: A bullet list analyzing key grammatical components of the sentence.
    ///    - Focus on the grammar concepts relevant to the skill being tested.
    ///    - Highlight verbs in <span style='color:#e74c3c'><b>red</b></span>, nouns/subjects in <span style='color:#3498db'><b>blue</b></span>, grammar rules/cases in <span style='color:#27ae60'><b>green</b></span>.
    ///    - Do NOT analyze every single trivial word. Merge concepts where natural.
    ///    Use: <p><b>Analysis:</b></p><ul><li>...</li></ul>
    ///
    /// 3. **Grammar Recap**: A summary box of the specific declensions, conjugations, or rules used.
    ///    Use: <div style='background-color:#3a3a3a;color:#e0e0e0;padding:10px;border-radius:5px;margin-top:10px;border-left:4px solid #3498db'><b>Grammar Recap:</b><br>...</div>
    ///
    /// IMPORTANT: No introductory or concluding chatter. No "Here is..." or "Great example!". Just the structured analysis.
    pub pedagogical_explanation: String,
    /// Morphological features of the TARGET word(s) — what the card tests.
    pub target_features: Vec<ExtractedFeature<M>>,
    /// Morphological features of the surrounding CONTEXT words.
    pub context_features: Vec<ExtractedFeature<M>>,
    /// Multi-word expressions (idioms, collocations, phrasal expressions) found in the sentence.
    #[serde(default)]
    pub multiword_expressions: Vec<MultiwordExpression>,
    /// Morpheme segmentation — present only for agglutinative languages.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub morpheme_segmentation: Option<Vec<WordSegmentation<F>>>,
}
