use std::fmt::Debug;
use std::hash::Hash;

use serde::{Deserialize, Serialize};

pub use crate::morphology_enums::*;

/// Common interface for language-specific morphology enums.
/// Allows generic code to extract the lemma and PoS label from any morphology variant.
pub trait MorphologyInfo {
    /// Auto-generated POS tag type for use in morpheme inventory `applies_to` fields.
    /// Generated by `#[derive(MorphologyInfo)]` as `<Name>PosTag`.
    type PosTag: Debug + Clone + Copy + PartialEq + Eq + Hash;

    /// The dictionary form of the word.
    fn lemma(&self) -> &str;
    /// The typed POS tag (variant of the auto-generated `<Name>PosTag` enum).
    fn pos_tag(&self) -> Self::PosTag;
    /// The part-of-speech label (e.g. "Noun", "Verb").
    fn pos_label(&self) -> &'static str;
}

/// Re-export `isolang::Language` as `IsoLang` so downstream crates don't need `isolang` directly.
pub use isolang::Language as IsoLang;

/// An ISO 15924 script code (e.g., "Latn", "Hira", "Kana").
/// Thin wrapper around a `&'static str` code. Use `.resolve()` to get full ISO data.
#[derive(Clone, Copy)]
pub struct Script(&'static str);

impl Script {
    pub const LATN: Script = Script("Latn");
    pub const CYRL: Script = Script("Cyrl");
    pub const HIRA: Script = Script("Hira");
    pub const KANA: Script = Script("Kana");
    pub const HANI: Script = Script("Hani");
    pub const ARAB: Script = Script("Arab");
    pub const HANG: Script = Script("Hang");

    /// Returns the 4-character ISO 15924 code.
    pub fn code(&self) -> &'static str {
        self.0
    }

    /// Constructs a `Script` from any valid ISO 15924 code string.
    /// Returns `None` if the code is not in the standard.
    pub fn new(code: &str) -> Option<Self> {
        let entry = iso15924::ScriptCode::by_code(code)?;
        Some(Script(entry.code.as_ref()))
    }

    /// Looks up the full ISO 15924 data for this script.
    pub fn resolve(&self) -> &'static iso15924::ScriptCode<'static> {
        iso15924::ScriptCode::by_code(self.0)
            .unwrap_or_else(|| panic!("Invalid ISO 15924 script code: {}", self.0))
    }
}

impl Debug for Script {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Script(\"{}\")", self.0)
    }
}

impl std::fmt::Display for Script {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.0)
    }
}

impl PartialEq for Script {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl Eq for Script {}

impl Hash for Script {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl Serialize for Script {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.0)
    }
}

impl<'de> Deserialize<'de> for Script {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let code = String::deserialize(deserializer)?;
        Script::new(&code)
            .ok_or_else(|| serde::de::Error::custom(format!("Unknown ISO 15924 script code: {code}")))
    }
}

/// Typological features of a language that influence its behavior or available card models.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TypologicalFeature {
    /// The language features verb conjugation (e.g. Polish, French, Spanish).
    Conjugation,
    /// The language is agglutinative (e.g. Turkish, Finnish, Korean).
    Agglutination,
}

/// Defines a language's linguistic properties for morphological feature extraction.
///
/// This is the core trait for Panini — it captures everything needed to extract
/// morphological features from text, independent of any particular application.
pub trait LinguisticDefinition {
    /// The language-specific morphology enum. Each variant represents a PoS category
    /// with its morphological fields (lemma, case, gender, aspect, etc.).
    type Morphology: Debug + Clone + Serialize + for<'de> Deserialize<'de>
        + schemars::JsonSchema + MorphologyInfo + Send + Sync;

    /// The grammatical function type for morpheme segmentation.
    /// Non-agglutinative languages set this to `()`.
    /// Agglutinative languages set this to their wrapper enum (e.g., `TurkishGrammaticalFunction`).
    type GrammaticalFunction: Debug + Clone + PartialEq
        + Serialize + for<'de> Deserialize<'de>
        + schemars::JsonSchema + Send + Sync;

    /// The ISO 639-3 language identity.
    fn iso_code(&self) -> IsoLang;

    /// The English name of the language, auto-derived from `iso_code()`.
    fn name(&self) -> &str {
        self.iso_code().to_name()
    }

    /// The scripts supported by this language.
    fn supported_scripts(&self) -> &[Script];

    /// The default script for the language.
    fn default_script(&self) -> Script;

    /// Language-specific extraction directives for the feature extractor.
    fn extraction_directives(&self) -> &str;

    /// Specific typological features of this language.
    fn typological_features(&self) -> &[TypologicalFeature] {
        &[]
    }

    /// Build the full JSON schema for feature extraction.
    fn build_extraction_schema(&self) -> serde_json::Value {
        let r#gen = schemars::SchemaGenerator::default();
        let schema = r#gen.into_root_schema_for::<
            crate::morpheme::FeatureExtractionResponse<Self::Morphology, Self::GrammaticalFunction>
        >();
        serde_json::to_value(&schema).unwrap()
    }

    /// Extra directives to append to the extraction prompt.
    fn extra_extraction_directives(&self) -> Option<String> { None }

    /// Post-process the morpheme segmentation returned by the LLM.
    fn post_process_extraction(
        &self,
        _segmentation: &mut Option<Vec<crate::morpheme::WordSegmentation<Self::GrammaticalFunction>>>,
    ) -> Result<(), String> {
        Ok(())
    }
}
