use serde::{Deserialize, Serialize};
use anyhow::Result;
use panini_core::traits::LinguisticDefinition;
use panini_core::morpheme::FeatureExtractionResponse;
use rig::completion::{CompletionModel, CompletionRequestBuilder};
use rig::message::Message;

use crate::llm_utils::clean_llm_json;
use crate::prompts::{build_extraction_prompt, ExtractorPrompts, ExtractionRequest};

/// Error returned when feature extraction parsing fails, carrying the raw LLM output.
#[derive(Debug)]
pub struct ExtractionParseError {
    pub raw_response: String,
    pub error_message: String,
}

impl std::fmt::Display for ExtractionParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.error_message)
    }
}

impl std::error::Error for ExtractionParseError {}

/// Previous failed attempt context for LLM self-correction retry.
pub struct PreviousAttempt {
    pub raw_response: String,
    pub error: String,
}

/// Extracts morphological features from text using an LLM via rig-core.
///
/// The caller provides any `rig::completion::CompletionModel` (OpenAI, Anthropic, etc.).
/// The JSON response schema is generated by the language definition and forwarded
/// to the provider via rig's `output_schema` mechanism.
pub async fn extract_features_via_llm<L, M>(
    language: &L,
    model: &M,
    request: &ExtractionRequest,
    temperature: f32,
    max_tokens: u32,
    previous_attempt: Option<&PreviousAttempt>,
    extractor_prompts: &ExtractorPrompts,
) -> Result<FeatureExtractionResponse<L::Morphology, L::GrammaticalFunction>>
where
    L: LinguisticDefinition + Send + Sync,
    L::Morphology: std::fmt::Debug
        + Clone
        + PartialEq
        + std::hash::Hash
        + Eq
        + Serialize
        + for<'de> Deserialize<'de>
        + schemars::JsonSchema
        + Send
        + Sync,
    L::GrammaticalFunction: std::fmt::Debug
        + Clone
        + PartialEq
        + Serialize
        + for<'de> Deserialize<'de>
        + schemars::JsonSchema
        + Send
        + Sync,
    M: CompletionModel,
{
    let system_prompt = build_extraction_prompt(language, request, extractor_prompts)?;

    // Convert panini's dynamic schema (serde_json::Value) into schemars::Schema.
    // schemars::Schema is a thin wrapper — this is a lossless round-trip.
    let schema_value = language.build_extraction_schema();
    let rig_schema: schemars::Schema = serde_json::from_value(schema_value.clone())?;

    let user_message = format!(
        "Extract features from this card:\n{}\n\nTARGET WORDS: {:?}",
        request.content, request.targets
    );

    // Build the message list. Use rig's low-level builder so we can pass
    // the full multi-turn history when retrying (self-correction).
    let mut builder: CompletionRequestBuilder<M> = model
        .completion_request(user_message.as_str())
        .preamble(system_prompt)
        .temperature(temperature as f64)
        .max_tokens(max_tokens as u64)
        .output_schema(rig_schema);

    // Append previous attempt context for self-correction if present.
    if let Some(prev) = previous_attempt {
        builder = builder
            .message(Message::assistant(&prev.raw_response))
            .message(Message::user(format!(
                "Your output is not conform to what I'm expecting. \
                 Please look at the error and correct yourself: {}",
                prev.error
            )));
    }

    let completion_response = builder.send().await?;

    // Extract the text content from the response.
    let raw_text = completion_response
        .choice
        .into_iter()
        .find_map(|c| {
            if let rig::completion::message::AssistantContent::Text(t) = c {
                Some(t.text)
            } else {
                None
            }
        })
        .ok_or_else(|| anyhow::anyhow!("LLM returned no text content"))?;

    let cleaned = clean_llm_json(&raw_text);
    let normalized = crate::llm_utils::normalize_pos_tags(cleaned);

    let mut response_parsed: FeatureExtractionResponse<L::Morphology, L::GrammaticalFunction> = match serde_json::from_str::<serde_json::Value>(&normalized) {
        Ok(json_value) => {
            // First pass: validate the JSON DOM against the JSON Schema to collect *all* typing errors
            if let Ok(validator) = jsonschema::validator_for(&schema_value) {
                let schema_errors: Vec<_> = validator.iter_errors(&json_value).collect();
                if !schema_errors.is_empty() {
                    let mut err_msgs = Vec::new();
                    for err in schema_errors {
                        err_msgs.push(format!("- Path: {}: {}", err.instance_path(), err));
                    }
                    let err_msg = format!("Schema validation failed with {} errors:\n{}", err_msgs.len(), err_msgs.join("\n"));
                    tracing::warn!(error = %err_msg, "Schema validation failed — retrying");
                    return Err(ExtractionParseError {
                        raw_response: normalized,
                        error_message: err_msg,
                    }.into());
                }
            }

            // Second pass: strongly-typed struct deserialization (should not fail if schema is valid)
            match serde_json::from_value(json_value) {
                Ok(parsed) => parsed,
                Err(e) => {
                    let err_msg = format!("Failed to deserialize valid DOM into struct: {}", e);
                    tracing::warn!(error = %err_msg, "Failed to deserialize");
                    return Err(ExtractionParseError {
                        raw_response: normalized,
                        error_message: err_msg,
                    }.into());
                }
            }
        }
        Err(e) => {
            let err_msg = format!("Invalid JSON syntax: {}", e);
            tracing::warn!(error = %err_msg, "Failed to parse JSON syntax");
            return Err(ExtractionParseError {
                raw_response: normalized,
                error_message: err_msg,
            }.into());
        }
    };

    // Run language-specific post-processing (morpheme validation for agglutinative languages).
    if let Err(e) = language.post_process_extraction(&mut response_parsed.morpheme_segmentation) {
        tracing::warn!(error = %e, "Morpheme post-processing failed — retrying");
        return Err(ExtractionParseError {
            raw_response: normalized,
            error_message: e,
        }
        .into());
    }

    Ok(response_parsed)
}
